# Blog settings
permalink: /blog/:title


# My variables
name: edulabs_0.1
description: Offene Bildung mit digital gestützten Methoden
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Pagination
#paginate: 3
#paginate_path: "/blog/page:num/"

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Gems
#gems: [jekyll-paginate]

